version: '3.8'

services:
  apache:
    build: 
      context: ./ 
      dockerfile: ./apache/Dockerfile 
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db
    
  db:
    image: mysql/mysql-server
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_pass
      MYSQL_DATABASE: db_test
      MYSQL_USER: user
      MYSQL_PASSWORD: my_pass
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306